const express = require('express');
const PDFDocument = require('pdfkit');
const prisma = require('../lib/prisma');
const { protect, requireTeacher } = require('../middleware/auth');
const router = express.Router();

// ─── GET /api/export/:lessonId/pdf ───────────────────────────────────────────
// Export a lesson as a formatted PDF download
router.get('/:lessonId/pdf', protect, requireTeacher, async (req, res) => {
  try {
    const { lessonId } = req.params;
    const { level } = req.query; // optional: foundational, gradeLevel, advanced

    const lesson = await prisma.lesson.findUnique({
      where: { id: lessonId },
      include: { class: { select: { teacherId: true, name: true } } },
    });

    if (!lesson || lesson.status !== 'READY') {
      return res.status(404).json({ error: 'Lesson not found or not ready' });
    }

    if (lesson.class.teacherId !== req.auth.userId) {
      return res.status(403).json({ error: 'Not authorized' });
    }

    // Log the export event
    await prisma.engagementEvent.create({
      data: {
        userId: req.auth.userId,
        lessonId,
        eventType: 'EXPORT_PDF',
        metadata: { level: level || 'all' },
      },
    }).catch(() => {});

    // Build the PDF
    const doc = new PDFDocument({ margin: 50 });
    const filename = `${lesson.title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    doc.pipe(res);

    // Title page
    doc.fontSize(24).font('Helvetica-Bold').text(lesson.title, { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(12).font('Helvetica').text(`Class: ${lesson.class.name}`, { align: 'center' });
    doc.fontSize(10).text(`Standard: ${lesson.standard}`, { align: 'center' });
    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
    doc.moveDown(1);

    // Determine which levels to include
    const levels = level
      ? [{ key: level, label: level.replace(/([A-Z])/g, ' $1').trim() }]
      : [
          { key: 'foundational', label: 'Foundational' },
          { key: 'gradeLevel', label: 'Grade Level' },
          { key: 'advanced', label: 'Advanced' },
        ];

    for (const { key, label } of levels) {
      const data = lesson[key];
      if (!data) continue;

      // Level header
      doc.fontSize(18).font('Helvetica-Bold').text(`${label} Level`, { underline: true });
      doc.moveDown(0.5);

      if (data.title) {
        doc.fontSize(14).font('Helvetica-Bold').text(data.title);
        doc.moveDown(0.3);
      }

      // Objectives
      if (data.objectives?.length) {
        doc.fontSize(12).font('Helvetica-Bold').text('Objectives:');
        data.objectives.forEach((obj) => {
          doc.fontSize(11).font('Helvetica').text(`  • ${obj}`);
        });
        doc.moveDown(0.5);
      }

      // Reading passage
      if (data.reading_passage) {
        doc.fontSize(12).font('Helvetica-Bold').text('Reading Passage:');
        doc.fontSize(11).font('Helvetica').text(data.reading_passage, { lineGap: 2 });
        doc.moveDown(0.5);
      }

      // Quiz
      if (data.quiz?.length) {
        doc.fontSize(12).font('Helvetica-Bold').text('Quiz:');
        data.quiz.forEach((q, i) => {
          doc.fontSize(11).font('Helvetica-Bold').text(`${i + 1}. ${q.question}`);
          if (q.options) {
            q.options.forEach((opt) => {
              doc.fontSize(10).font('Helvetica').text(`    ${opt}`);
            });
          }
          doc.fontSize(10).font('Helvetica-Oblique').text(`    Answer: ${q.answer}`);
          doc.moveDown(0.2);
        });
        doc.moveDown(0.3);
      }

      // Discussion prompts
      if (data.discussion_prompts?.length) {
        doc.fontSize(12).font('Helvetica-Bold').text('Discussion Prompts:');
        data.discussion_prompts.forEach((p) => {
          doc.fontSize(11).font('Helvetica').text(`  • ${p}`);
        });
        doc.moveDown(0.5);
      }

      // Extension activities
      if (data.extension_activities?.length) {
        doc.fontSize(12).font('Helvetica-Bold').text('Extension Activities:');
        data.extension_activities.forEach((a) => {
          doc.fontSize(11).font('Helvetica').text(`  • ${a}`);
        });
        doc.moveDown(0.5);
      }

      // Separator between levels
      doc.moveDown(0.5);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#eeeeee');
      doc.moveDown(0.5);
    }

    // Footer
    doc.fontSize(8).font('Helvetica').text(
      `Generated by EduForge on ${new Date().toLocaleDateString()}`,
      50,
      doc.page.height - 50,
      { align: 'center' }
    );

    doc.end();
  } catch (err) {
    // Only send JSON error if headers haven't been sent yet
    if (!res.headersSent) {
      res.status(500).json({ error: err.message });
    }
  }
});

module.exports = router;