const express = require('express');
const crypto = require('crypto');
const router = express.Router();
const prisma = require('../lib/prisma');
const { requireTeacher } = require('../middleware/auth');
const { generateLesson } = require('../services/lessonforge');
const demoStore = require('../services/demo-store');

const generationCache = new Map();
const inflightGenerations = new Map();
const CACHE_TTL_MS = Number(process.env.LESSONFORGE_CACHE_TTL_MS || 1000 * 60 * 60 * 6);
const MAX_CACHE_ENTRIES = Number(process.env.LESSONFORGE_CACHE_MAX_ENTRIES || 50);

function normalizeCacheText(value) {
  return String(value || '').trim().replace(/\s+/g, ' ');
}

function getCacheKey({ standard, gradeLevel, subject }) {
  const cacheInput = JSON.stringify({
    standard: normalizeCacheText(standard).toLowerCase(),
    gradeLevel: normalizeCacheText(gradeLevel),
    subject: normalizeCacheText(subject).toLowerCase(),
  });

  return crypto.createHash('sha256').update(cacheInput).digest('hex');
}

function cloneLesson(lesson) {
  return JSON.parse(JSON.stringify(lesson));
}

function readCachedGeneration(cacheKey) {
  const cached = generationCache.get(cacheKey);
  if (!cached) return null;

  if (Date.now() - cached.createdAt > CACHE_TTL_MS) {
    generationCache.delete(cacheKey);
    return null;
  }

  return cloneLesson(cached.lesson);
}

function writeCachedGeneration(cacheKey, lesson) {
  if (generationCache.size >= MAX_CACHE_ENTRIES) {
    const oldestKey = generationCache.keys().next().value;
    if (oldestKey) generationCache.delete(oldestKey);
  }

  generationCache.set(cacheKey, {
    createdAt: Date.now(),
    lesson: cloneLesson(lesson),
  });
}

// ─── POST /api/lessonforge/generate ──────────────────────────────────────────
// Accepts a curriculum standard + context and returns 3-tier differentiated
// lesson plans (foundational / grade-level / advanced) generated by Claude.
router.post('/generate', requireTeacher, async (req, res) => {
  const { standard, gradeLevel = '6', subject = 'ELA', description } = req.body;

  if (!standard || !standard.trim()) {
    return res.status(400).json({ error: 'standard is required' });
  }
  if (standard.length > 2000) {
    return res.status(400).json({ error: 'Standard text must be under 2000 characters' });
  }

  // Append teacher notes to the standard so Claude factors them in
  const fullStandard = description?.trim()
    ? `${standard}\n\nTeacher context: ${description}`
    : standard;

  try {
    const cacheKey = getCacheKey({ standard: fullStandard, gradeLevel, subject });
    const cached = readCachedGeneration(cacheKey);
    if (cached) {
      return res.json({ ...cached, _cached: true });
    }

    let generation = inflightGenerations.get(cacheKey);
    if (!generation) {
      generation = generateLesson(fullStandard, gradeLevel, subject)
        .then((result) => {
          writeCachedGeneration(cacheKey, result);
          return result;
        })
        .finally(() => {
          inflightGenerations.delete(cacheKey);
        });
      inflightGenerations.set(cacheKey, generation);
    }

    const result = await generation;
    res.json(cloneLesson(result));
  } catch (err) {
    console.error('LessonForge /generate error:', err);
    res.status(500).json({ error: 'Lesson generation failed', detail: err.message });
  }
});

// ─── POST /api/lessonforge/save ──────────────────────────────────────────────
// Persists a fully generated lesson into PostgreSQL (Supabase).
router.post('/save', requireTeacher, async (req, res) => {
  const {
    classId,
    className = 'My Class',
    title,
    standard,
    lesson,
  } = req.body;

  if (!standard || !standard.trim()) {
    return res.status(400).json({ error: 'standard is required' });
  }

  if (!lesson || !lesson.foundational || !lesson.gradeLevel || !lesson.advanced) {
    return res.status(400).json({ error: 'lesson with foundational, gradeLevel, and advanced is required' });
  }

  try {
    const teacherId = req.auth?.userId || req.user?.id;
    let targetClassId = classId;

    if (demoStore.isDemoStoreEnabled()) {
      const saved = demoStore.saveLesson({
        classId,
        className,
        title,
        standard,
        lesson,
        teacherId,
      });
      if (!saved) return res.status(403).json({ error: 'Class not found or access denied' });
      return res.status(201).json({
        lesson: {
          id: saved.id,
          classId: saved.classId,
          title: saved.title,
          status: saved.status,
          publishedAt: saved.publishedAt,
          createdAt: saved.createdAt,
        },
      });
    }

    if (targetClassId) {
      const found = await prisma.class.findFirst({
        where: { id: targetClassId, teacherId },
        select: { id: true },
      });

      if (!found) {
        return res.status(403).json({ error: 'Class not found or access denied' });
      }
    } else {
      const draftClassName = className?.trim() || 'LessonForge Drafts';
      const existingDraftClass = await prisma.class.findFirst({
        where: { teacherId, name: draftClassName },
        select: { id: true, name: true },
      });

      if (existingDraftClass) {
        targetClassId = existingDraftClass.id;
      } else {
        const createdClass = await prisma.class.create({
          data: {
            name: draftClassName,
            teacherId,
          },
          select: { id: true, name: true },
        });
        targetClassId = createdClass.id;
      }
    }

    const saved = await prisma.lesson.create({
      data: {
        classId: targetClassId,
        standard: standard.trim(),
        title: title?.trim() || lesson.title || 'Untitled Lesson',
        status: 'READY',
        foundational: lesson.foundational,
        gradeLevel: lesson.gradeLevel,
        advanced: lesson.advanced,
      },
      select: {
        id: true,
        classId: true,
        title: true,
        status: true,
        publishedAt: true,
        createdAt: true,
      },
    });

    res.status(201).json({ lesson: saved });
  } catch (err) {
    console.error('LessonForge /save error:', err);
    res.status(500).json({ error: 'Failed to save lesson', detail: err.message });
  }
});

module.exports = router;
