const express = require('express');
const router = express.Router();
const { generateLesson } = require('../services/lessonforge');

// ─── POST /api/lessonforge/generate ──────────────────────────────────────────
// Accepts a curriculum standard + context and returns 3-tier differentiated
// lesson plans (foundational / grade-level / advanced) generated by Claude.
router.post('/generate', async (req, res) => {
  const { standard, gradeLevel = '6', subject = 'ELA', description } = req.body;

  if (!standard || !standard.trim()) {
    return res.status(400).json({ error: 'standard is required' });
  }
  if (standard.length > 2000) {
    return res.status(400).json({ error: 'Standard text must be under 2000 characters' });
  }

  // Append teacher notes to the standard so Claude factors them in
  const fullStandard = description?.trim()
    ? `${standard}\n\nTeacher context: ${description}`
    : standard;

  try {
    const result = await generateLesson(fullStandard, gradeLevel, subject);
    res.json(result);
  } catch (err) {
    console.error('LessonForge /generate error:', err);
    res.status(500).json({ error: 'Lesson generation failed', detail: err.message });
  }
});

module.exports = router;
